services:
  - type: web
    name: my-web-service
    env: python
    buildCommand: |
      export CARGO_HOME=/opt/render/project/.cargo
      export RUSTUP_HOME=/opt/render/project/.rustup
      pip install maturin
      pip install .

      # 升级 pip/wheel/maturin
      pip install --upgrade pip setuptools wheel maturin

      # 安装 Python 依赖
      pip install --no-cache-dir -r requirements.txt

      # 前端打包
      cd frontend
      npm install
      npm run build
      cd ..

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: CARGO_HOME
        value: /opt/render/project/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/project/.rustup
        
      # 数据库
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

      # Telegram Bot
      - key: BOT_TOKEN
        sync: false
      - key: BOT_ADMINS
        sync: false
      - key: DEFAULT_LANG
        value: zh

      # 支付
      - key: PAYMENT_SANDBOX
        value: false
      - key: PAYMENT_API_KEY
        sync: false
      - key: PAYMENT_API_BASE
        value: "https://api.alipay.com/v1"
