services:
  - type: web
    name: my-fastapi-bot
    env: python
    plan: free
    buildCommand: |
      # 设置 Rust 缓存到用户目录
      export CARGO_HOME=$HOME/.cargo
      export RUSTUP_HOME=$HOME/.rustup

      # 升级 pip、setuptools、wheel、maturin
      pip install --upgrade pip setuptools wheel maturin

      # 安装依赖
      pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_ADMINS
        sync: false
      - key: PAYMENT_SANDBOX
        value: "false"
      - key: PAYMENT_API_KEY
        sync: false
      - key: PAYMENT_API_BASE
        value: "https://api.alipay.com/v1"
