services:
  - type: web
    name: my-fastapi-bot
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip setuptools wheel maturin
      pip install --no-cache-dir -r requirements.txt

      cd frontend
      npm install
      npm run build
      cd ..

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: ENV
        value: production
      - key: LOG_LEVEL
        value: INFO

      # Rust 缓存位置，必须设置
      - key: CARGO_HOME
        value: /opt/render/project/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/project/.rustup

      # 数据库
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

      # Telegram Bot
      - key: BOT_TOKEN
        sync: false
      - key: BOT_ADMINS
        sync: false
      - key: DEFAULT_LANG
        value: zh

      # 支付
      - key: PAYMENT_SANDBOX
        value: false
      - key: PAYMENT_API_KEY
        sync: false
      - key: PAYMENT_API_BASE
        value: "https://api.alipay.com/v1"

      - key: CARGO_HOME
      value: /opt/render/project/.cargo
      - key: RUSTUP_HOME
      value: /opt/render/project/.rustup  
