services:
  - type: web
    name: my-fastapi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql+asyncpg://YOUR_USER:YOUR_PASS@YOUR_HOST:5432/YOUR_DB"
      - key: REDIS_URL
        value: "redis://YOUR_REDIS_USER:YOUR_REDIS_PASS@YOUR_REDIS_HOST:6379/0"
      - key: PAYMENT_API_BASE
        value: "https://api.alipay.com/v1"
      - key: BOT_ADMINS
        value: "123456,654321"
      - key: BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
