services:
  - type: web
    name: my-fastapi-bot
    env: python
    plan: free

    buildCommand: |
      # 解决 Rust 只读文件系统问题（maturin依赖）
      export CARGO_HOME=$HOME/.cargo
      export RUSTUP_HOME=$HOME/.rustup

      # 升级 pip/wheel/maturin
      pip install --upgrade pip setuptools wheel maturin

      # 安装 Python 依赖
      pip install --no-cache-dir -r requirements.txt

      # 前端打包
      cd frontend
      npm install
      npm run build
      cd ..

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: ENV
        value: production
      - key: LOG_LEVEL
        value: INFO

      # 数据库
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

      # Telegram Bot
      - key: BOT_TOKEN
        sync: false
      - key: BOT_ADMINS
        sync: false
      - key: DEFAULT_LANG
        value: zh

      # 支付
      - key: PAYMENT_SANDBOX
        value: false
      - key: PAYMENT_API_KEY
        sync: false
      - key: PAYMENT_API_BASE
        value: "https://api.alipay.com/v1"
